My home nixos/nix-darwin configuration rewrite in flakelight

This is a work in progress. Don't abuse it yet.

Its main raison d'etre is to do disk setup/partitioning via disko and autogeneration of stuff. As well as to get deploy-rs to do all the rest of the work so I can do deploys of things from one location out to remote systems over ssh.

Todos:
- ssh ca setup so I can use an ssh ca setup for all ssh internally
- wireguard setup so I can setup my own overlay vpn for everything
- figure out the home manager activation issue:
#+begin_src
[FAILED] Failed to start Home Manager environment for mitch.
See 'systemctl status home-manager-mitch.service' for details.
...
vm-simple systemd[1]: Starting Home Manager environment for mitch...
vm-simple hm-activate-mitch[710]: Starting Home Manager activation
vm-simple hm-activate-mitch[710]: Could not find suitable profile directory, tried /home/mitch/.local/state/nix/profiles and /nix/var/nix/profiles/per-user/mitch
#+end_src

Its complaining about profiles

* Testing via qemu/vm

I have a truly hacky script/wrapper around qemu in the bin dir, [[file:bin/test-iso][test-iso]]. Its a hacky simple way to test out derivations.

For now it defaults to the vm setup in nix/nixosConfigurations/vm-simple

This is a temporary state for now, I hope, its mostly to bootstrap into a fully automated install again. I want to figure out how to replace this script with "normal" nixos testing infra in python like the nixos/nixpkgs repo has.

For now quick hacks is fine. Also useful for testing "air-gap" use cases as I can just disable network on qemu.

Below here be old readme I haven't updated. Its likely not applicable any longer.

* My home network nix flake setup

  So my goal with all this is to get as much into a NixOS layout for home. Now that Flakes are "kinda/sorta" out it seems the best time to convert everything over to flakes.

** Nix resources

  Because nix isn't exactly a "common" thing to encounter as a programming language/package manager...

  - https://nixos.org/guides/nix-pills/
  - https://nix.dev/
  - https://github.com/tazjin/nix-1p
  - https://learnxinyminutes.com/docs/nix/
  - https://teu5us.github.io/nix-lib.html
  - https://ryantm.github.io/nixpkgs/functions/library/strings/
  - https://wiki.nikitavoloboev.xyz/operating-systems/linux/nixos
  - https://stephank.nl/p/2020-06-01-a-nix-primer-by-a-newcomer.html
  - https://ertt.ca/nix/patch-nixpkgs/
  - https://nixos.org/manual/nix/stable/introduction (reference guide to the language)

  NixOS option search, for when you want to know what you can set.
  https://search.nixos.org/options
  https://nixos.org/manual/nix/stable/language/builtins.html?search=mkIf

  Home-manager equivalent.

https://mipmip.github.io/home-manager-option-search/?query=

  A nice cli that searches both is https://github.com/mlvzk/manix


** Rough usage

   So the flake has deploy targets setup already for deploy-rs, to update/rebuild all NixOS nodes run:

#+begin_src shell
clear; nix flake check --show-trace && nix run github:serokell/deploy-rs -- -s .
#+end_src

   Or use the wrapper function+script in [[file:static/src/lib.sh][lib.sh]] and [[file:src/rebuild.zsh][rebuild]] script:

#+begin_src shell
wtf rebuild
#+end_src

   To run a deploy without running *nix flake check*:

#+begin_src shell
CHECK=anyvalue wtf rebuild
#+end_src

And should be good to go. Caveats on how/where deploy-rs can deploy to aside. Aka that without builder setup cannot deploy to a macos system from linux. This is on my TODO list to fix at some point.

** Layout

   Since I'm trying to document things a bit more a bit of layout convention explanation:

   - [[file:bin/][bin]]     Simply a directory for any pertinent scripts that use this repo. Note none of these scripts end up in */nix/store*.
   - [[file:src/][src]]     Source for stuff in bin.
   - [[file:hosts/][hosts]]   Host specific data, e.g. mostly generated nix configuration files.
   - [[file:img/][img]]     Nixos specific directory where iso or disk image outputs get dumped.
   - [[file:modules/][modules]] General directory for any modules for nixos, nix-darwin, and home-manager. Should be intended to encompass "stuff with options". Also includes the img autoinstall module used for iso builds.
   - [[file:patches/][patches]] Any patch files that may be needed for things like CVE's that might not yet be upstream yet in nixpkgs or anywhere else.
   - [[file:secrets/][secrets]] Any secret related data for age and/or git-transcrypt. Basically "private junk hiding in plain sight".
   - [[file:static/][static]]  Bucket for any static files, which generally amounts to either fragments or full bits of files like say *.profile* that the rest of the flake will use.

* Todo's
** NixOS

I need to brain up how exactly I want to do mirroed systemd boot setups.

My current setup that I abused with zfs is basically just rsync the data from the primary boot disk to the rest.

This is hacky and it needs tests/proof.

#+begin_src
    boot.loader.systemd-boot.extraInstallCommands = ''
      set -e
      ${pkgs.util-linux}/bin/mountpoint -q /efiboot/efi0 || ${pkgs.util-linux}/bin/mount -t vfat -o iocharset=iso8859-1 /dev/disk/by-partlabel/ESP0 /efiboot/efi0
      ${pkgs.util-linux}/bin/mountpoint -q /efiboot/efi1 || ${pkgs.util-linux}/bin/mount -t vfat -o iocharset=iso8859-1 /dev/disk/by-partlabel/ESP1 /efiboot/efi1
      ${pkgs.rsync}/bin/rsync -Havz --exclude .lost+found --delete --delete-before /efiboot/efi0/ /efiboot/efi1
    '';
#+end_src

The upstream nixos pr to add it was this:
https://github.com/NixOS/nixpkgs/pull/246897

Of note:
https://serverfault.com/questions/1101507/how-should-the-efi-system-partition-be-made-redundant-without-using-hardware-rai

I am thinking I should just make my own nixosModule that does:
- On systemd-boot updates do the rsyncs to the mirrored boot devices/partitions
- efibootmgr install to the boot devices with an increment of 1 to specify the boot order for things
- That should do it.

Non goals:
- I don't care about windows/other os's here. That is nixos is the only os
- Not dealing with encryption related stuff for now, future mitch problem
- Its not intended to be perfect

Goals:
- Just be able to boot a system without rebuilding if the primary disk fails
- Thats it, its not meant to be forever, more than likely I will be rebuilding anyway just want to be able to have resiliency to hardware failures


** Macos

Nice lists of open source stuff to poke at someday.
https://github.com/serhii-londar/open-source-mac-os-apps
https://github.com/jaywcjlove/awesome-mac

** Macos Emacs

Try out more patches from here? https://tdodge.consulting/blog/living-the-emacs-garbage-collection-dream

https://github.com/tyler-dodge/emacs/commit/b386047f311af495963ad6a25ddda128acc1d461.patch

Some interesting org packages here.
https://github.com/chrisbarrett/nursery

Some interesting macos integration ideas.
https://xenodium.com/emacs-macos-sharing-dwim-style-improved/
https://github.com/xenodium/dwim-shell-command/commit/20e782b4bf1ea01fecfce3cc8ac4c5a74518cd80

Need to try out xwidget support and nov-xwidget on macos
https://macowners.club/posts/using-xwidgets-on-macos/
and
https://github.com/chenyanming/nov-xwidget

Also need to start abusing anki+org notes for cards
https://yiufung.net/post/anki-org/

And explore this for org notes to auto get graphviz images into docs.
https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-dot.html

Set this up?
https://en.liujiacai.net/2022/11/26/oh-my-github-1-0/

** Fonts

Add or try em?

https://input.djr.com/info/
https://www.fontget.com/font/among-us
https://www.fontget.com/font/among-us-filled/
https://www.monolisa.dev/
https://github.com/intel/intel-one-mono
https://www.fontbolt.com/font/barbie-2023-font/

** Linode

Need to get vps using nix as well now that 22.11 has image build support.

https://github.com/Vanilla-s-Lab/linode-nix/tree/master

** Network booting?

  Might be fun to look into for a pi4 k8s cluster or something.

  https://github.com/DeterminateSystems/nix-netboot-serve

* Random notes

Cause I forget and this is a readme so why not stick it here:

** List generations

List out nixos generations as root:

#+begin_src sh
nix-env --list-generations --profile /nix/var/nix/profiles/system
#+end_src

** Rollback to prior generation

Switch/rollback to prior generation, also as root:

#+begin_src sh
nixos-rebuild switch --rollback
#+end_src
** Rolling back to a specific generation

Cause sometimes *nixos-rebuild switch --rollback* isn't enough or you have multiple generations that are no good.

#+begin_src shell
nix-env --switch-generation $GENERATION --profile /nix/var/nix/profiles/system
/nix/var/nix/profiles/system/bin/switch-to-configuration switch
#+end_src
