* My home network nix flake setup

  So my goal with all this is to get as much into a NixOS layout for home. Now that Flakes are "kinda/sorta" out it seems the best time to convert everything over to flakes.

** Potent Notables

   So what in here is worth looking at exactly? Well this is a combined NixOS and x86 Macos setup with home manager. That is, while its incomplete I manage both my macos laptop and any/all NixOS nodes from this shared flake repo.

   There is also iso generation and autoinstall setup as well, for that reference [[file:modules/iso/autoinstall.nix][this autoinstall module]]. As well as the generators in [[file:flake.nix][flake.nix]] (search for iso).

   My current setup is basically build an iso that will autoinstall nixos onto a system then poweroff/reboot and from there I can pivot that install into this install via deploy-rs.

   On the deploy-rs note, the flake file also has those.

   I am also using or rather trying to use sops to handle secrets like passwords etc...

** Rough usage

   So the flake has deploy targets setup already for deploy-rs, to update/rebuild all NixOS nodes run:

#+begin_src shell
clear; nix flake check --show-trace && nix run github:serokell/deploy-rs -- -s .
#+end_src

   Or use the wrapper function in [[file:home/.profile][.profile]]:

#+begin_src shell
deploy
#+end_src

   To run a deploy with a *nix flake check* run:

#+begin_src shell
deploy check
#+end_src


And should be good to go. Caveats on how/where deploy-rs can deploy to aside. Aka that without builder setup cannot deploy to a macos system from linux. This is on my TODO list to fix at some point.
