[formatter.nix]
command = "nixfmt"
includes = ["**/*.nix"]
#includes = ["nix/**/*.nix", "flake.nix", "treefmt.nix"]

[formatter.sh]
command = "altshfmt"
# TODO: Have a lot of mksh/search/replace non posix stuff to fix
#includes = ["**/*.sh"]
includes = ["bin/**/*", "src/**/*.sh"]