#-*-mode: Shell-script; coding: utf-8;-*-
# Installer only zshrc config
set -o emacs

# Load common iso shell lib functions
# Run something as root depending on user
asroot() {
  if [ "$(id -u)" -ne 0 ]; then
    sudo "$@"
  else
    "$@"
  fi
}

# To find all the /dev/disk/... symlinks to a target device
# input could be like:
# sda|/dev/sda, so just see if its a block device first then prepend
# /dev/ to it and try that if it fails it fails.
disklinks() {
  target="${1?need a target bra}"

  if [ ! -b "${target}" ]; then
    target="/dev/${target}"
  fi
  asroot find -L /dev -xdev -samefile "${target}"
}

alias syso="echo o | asroot tee /proc/sysrq-trigger"
alias sysb="echo b | asroot tee /proc/sysrq-trigger"

alias off="asroot systemctl poweroff"
alias tofw="asroot systemctl reboot --firmware-setup"

alias autostatus="asroot systemctl status autoinstall"
alias autorestart="asroot systemctl restart autoinstall"
alias autof="journalctl -fu autoinstall"
alias autoc="journalctl -u autoinstall | cat"

inst() {
  asroot disko
  asroot nixos-generate-config --root /mnt
  asroot install -m644 /etc/machine-id /mnt/etc/machine-id

  # This is all a huge hack I need to install the nixos system config for the target
  #
  # How the hell do I do that without recursion though... my iso hack works but
  # means I have an "iso" configuration that embeds the target configuration.
  #
  # I'd like to remove that duplication somehow...
  asroot sed -i '/^\}$/i\boot.kernelParams = [ "console=tty0" "console=ttyS0,115200n8" "console=ttyAMA0,115200n8" ];' /mnt/etc/nixos/configuration.nix
  asroot sed -i '/&\}$/i\boot.loader.systemd-boot.consoleMode = "auto";' /mnt/etc/nixos/configuration.nix

  asroot nixos-install --no-root-password
}
