#!/usr/bin/env sh
#-*-mode: Shell-script; coding: utf-8;-*-
# SPDX-License-Identifier: BlueOak-1.0.0
# Description: macos only reopen command to make close+open -a apps easy peasy.
if [ $# -lt 1 ]; then
  printf "usage: %s app_name\n" "$0" >&2
  exit 1
fi

set -e

for app in "$@"; do
  printf "reopening: %s\n" "${app}" >&2
  osascript << END
tell application "${app}"
    quit
end tell
END

  # Some of these gooey apps seem to start then fail but restarting works, so
  # leat the caller know if the restart didn't result in the app running.
  lim=0
  until pgrep -lf "${app}" > /dev/null 2>&1; do
    # note -j so the app(s) are hidden by default as this is called non
    # interactively so no good in having an app jump to the front of the line.
    open -j -a "${app}"

    sleep 3
    lim=$((lim + 1))
    if [ "${lim}" -gt 3 ]; then
      exit 1
    fi
  done
done
