name: Find latest versions of stuff I use
on:
  schedule:
    - cron: "15 1 * * 0"
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: aldoborrero/direnv-nix-action@v2
        if: ${{ inputs.enable_direnv_nix_action }}
        with:
          use_nix_profile: false
          nix_channel: nixpkgs
      - run: ./bin/versions
