name: Update flake.lock
on:
  schedule:
    - cron: "15 1 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: rm -f flake.lock
      - run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Update flake.lock
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
