users:
    root: ENC[AES256_GCM,data:aUiMyQclOaInSlzVwSNOlQQ89LIIi4HlEa5oIoQ5uw==,iv:O/RZa2cFF2XYXMiCqpKxsnxNNQokhiabheaOh/EiXUE=,tag:MZL/Pp/QfMIbg70lkngM9g==,type:str]
    mitch: ENC[AES256_GCM,data:gkGADrrYVKtGR0L0I1Xgmy6EhXcoZoAptXPj/yppJw==,iv:BzJqDIDBd0DCY5b8qk2HnuqfSTgreK3Nu8wWBIqKioo=,tag:VoZuWIw+X1EUpVnEy11Pbg==,type:str]
restic:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:nluBfg==,iv:3jbeQrtlAi5QEoOYLy/yXdM1KUd1P8Ibdv2YqdnRX2Q=,tag:eYnPSjnd+/PbD4tMdxg9iQ==,type:str]
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:v9Qk8ThWe5KOc21Eqx+9omeyffid34y6MyI=,iv:hTtsS1GEdjnnIHXuDbEc69Mpzm2Y6NUHu4e4S4qLi0c=,tag:3cSUs5mdJb7o/q4l2EiLhg==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:VK5q58YvelfqnKJoeGHXKQ7fxNwaI9gpq0CEZJUmUuYZFqkA+UJ9P9p2GCltaj7LBvoixeqYSr4sXAiZOPPkiA==,iv:lIxWb3DeAouGxmJFLhgCCQrA3trsTpCVGd619a5oVXQ=,tag:oZ0CPE6v1Q0gbd0FhjyQ2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wq29cka9ryvdyrdlyxhuqturqpsf5c9djhdkeqkcex9pht39s9pspatxsc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ekFaK0o3dGZGN01BVXFi
            T3RiL0J3OWhkWmI3dy9xdWd6blFhWllST0RJCmNOYkNNZTh2QVBURjQwaU4zZXl2
            S2lDRUxscENsalpHWVlsVjJZN0JvRUkKLS0tIFlsUlZhUFFrOFU2TlIvOFZ0TUlW
            Vkp4Y0NkUnFxd3pSbERjUHp1VnBNWFEKif/4ViqF9NJRaAAiGjUGp6pa5i3EBbtX
            k8aPkATvsmnlPUGQJg/zOkTRw0iL9zlbiyd8t/aopP7UhXo2zXRrWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19apnr33azl9nvqtvtc82ualcmzgc34y8yur7jfjtekqdkfard3tqk0jc3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bG9rUDI3L2t1dE9qNEZu
            SXpma1lHQWlZVnNwdGJRTDFLdEpxbUZSTnlBCnVpb0w5RS9GVWY5TjZZTThrNngv
            Q2NzL2pESDFxMHh1Y0RITkl0MTg1UUkKLS0tIDI2dDFQb3YzNExBSmxvZDlTdXZQ
            UWI2dEdBd1REOU5BQ0RSL0NIV3VSN3cKmPNh+Axu5gZMQ/TWXHRMRPKEcCsKbdnx
            9gw2LDDBAINUr7kd+xD/CHbp7Qn0pcWfHExN0ELu3XU5wCFDFNrAyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ltz98j0yhj3rcmfg6aqhq7m6qwhfcpxpfzh0xwclwxr3ce0xgf7qrml2vn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMWZycFIvWlhjWU1kdC9Q
            cHJNdGFwYU5xeVFsTktzODlPK3B0QnozQ0ZrCjdZNm1PWkk1TGNia2FkbDB3WlNv
            bkpxOW82eUVmak9DaFh5c0liOTg2Wk0KLS0tIHV3NHVDaFN2TWlGMEZBbzhQelBL
            bC9PMzg0UWRDYWU0SUdvY2xkeVdxWlUK1kFOkXffAjw+4haHh+ISM8OrVDMxDDvM
            C6+TubjKWg1kkRlcCRhcrmHQZj1MhkR/CCInIMdqHyEJ22BrFF4zPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-06T03:37:38Z"
    mac: ENC[AES256_GCM,data:GZhnG5GjexhHQOGdwDuylL59FxCtVKIrM5UB+E3LTm2W+hzZTN8ZdMcXmoyhEsK/zaKh7Ss+N9gUA5zDdVxXA941bOe8t5Ckf1eq7kOaj04ssyLSDFWLZ/GBAPcaqfiL16p+uyhbUiarLFAJNohVA3Oqxfyn4jc3I0kD4PQGzoM=,iv:xCWtGRgBPB7+IBIluIMFkznBfDLGDjw1z3Mut7LM1Jg=,tag:81Wd9YuMA+lIoqjBKtSRWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
